apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "website-nodejs-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ template "website-nodejs-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "website-nodejs-chart.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: MONGODB_URI
          value: {{ .Values.mongodbUri }}
