apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-nodejs
  template:
    metadata:
      labels:
        app: website-nodejs
    spec:
      containers:
      - name: website-nodejs
        image: aeramzy9/website-nodejs:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: website-nodejs-service
spec:
  selector:
    app: website-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
