apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-nodejs
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-nodejs
  template:
    metadata:
      labels:
        app: website-nodejs
    spec:
      containers:
      - name: website-nodejs
        image: aeramzy9/website-nodejs:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb-service.argocd.svc:27017/hello-world       
---
apiVersion: v1
kind: Service
metadata:
  name: website-nodejs-service
  namespace: argocd  
spec:
  selector:
    app: website-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
